trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-functions-playwright'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'Demo Account'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'CI'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'demo-function-playwright-ci'
    resourceGroupName: 'demo-function-playwright-ci'
    storageAccountName: 'azfplaywrightci'
    region: 'East US'
    packageName: 'App.zip'
